/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Restaurant = IDL.Record({
  'area' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'emoji' : IDL.Text,
  'priceRange' : IDL.Text,
  'cuisine' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAttraction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addCuisine' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addDemographics' : IDL.Func([IDL.Text], [], []),
  'addFact' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addOverview' : IDL.Func([IDL.Text], [], []),
  'addRestaurant' : IDL.Func([Restaurant], [], []),
  'getAttractions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getCuisine' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getDemographics' : IDL.Func([], [IDL.Text], ['query']),
  'getFacts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getOverview' : IDL.Func([], [IDL.Text], ['query']),
  'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getRestaurantsCount' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Restaurant = IDL.Record({
    'area' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'emoji' : IDL.Text,
    'priceRange' : IDL.Text,
    'cuisine' : IDL.Text,
  });
  
  return IDL.Service({
    'addAttraction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addCuisine' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addDemographics' : IDL.Func([IDL.Text], [], []),
    'addFact' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addOverview' : IDL.Func([IDL.Text], [], []),
    'addRestaurant' : IDL.Func([Restaurant], [], []),
    'getAttractions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getCuisine' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getDemographics' : IDL.Func([], [IDL.Text], ['query']),
    'getFacts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getOverview' : IDL.Func([], [IDL.Text], ['query']),
    'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getRestaurantsCount' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };